### PR TITLE
Ch deploy to heroku 161340169

### PR DESCRIPTION
**Pull request by WalterNyeko**
#### What does this PR do?
Ensures that the app is deployed to Heroku and can be accessed at any time by the PO or TTL.
#### Description of Task to be completed?
Deployment to Heroku
#### How should this be manually tested?
[Visit this URL to access the app on Heroku](https://authors-haven-odin.herokuapp.com/admin)
#### What are the relevant pivotal tracker stories?
[#161340169](https://www.pivotaltracker.com/story/show/161340169)

### CODE REVIEW

**Comment by nakatuddesuzan** [comment]
Hey @JSnakegitHub good work here , but i want to ask, why are some lines of code commented out?  If they are not important, how about they are deleted.

**Comment by WalterNyeko** [comment]
Hey Sue, they are important locally but not when they get deployed in
Heroku...I think I will use an OR to make it work both sides

**Comment by nakatuddesuzan** [comment]
Okay i get it

**Review by wycliffkas — COMMENTED** [review]
Looks good to me

**Review by wycliffkas — DISMISSED** [review]

**Comment by daud1** [comment]
Hey @JSnakegitHub , please resolve the merge conflicts that this branch has with `develop` before I can merge it in.

**Review by nakatuddesuzan — APPROVED** [review]
LGTM

**Pull request merged**
