### PR TITLE
#161340168 configure use PostgreSQL as DB engine

### PR DESCRIPTION
**Pull request by nakatuddesuzan**
#### What does this PR do?
Configure Authors Haven to use PostgreSQL as DB Engine
#### Description of Task to be completed?
Edited database settings to make PostgreSQL the default database
Added environment variables to be used
#### How should this be manually tested?
This can be tested using Postico
#### What are the relevant pivotal tracker stories?
[#161340168](https://www.pivotaltracker.com/story/show/161340168)
#### Screenshots (if appropriate)
screen shot 2018-10-24 at 11 37 43

### CODE REVIEW

**Review by krmroland — COMMENTED** [review]
Neat

**Review by krmroland — DISMISSED** [review]
LGTM

**Review by krmroland — APPROVED** [review]
LGTM

**Review by Musacoli — APPROVED** [review]
LGTM
Nicely done Suzan
👌👌👌

**Pull request merged**
